name: Deploy PR previews

concurrency: preview-${{ github.ref }}

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # WE REMOVED THE NPM INSTALL AND NPM RUN BUILD STEPS

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .        # Changed from ./build/ to . (the root folder)
          preview-branch: gh-pages
